sudo: required
services: docker
language: generic
notifications:
  slack:
    rooms:
      secure: aNpX4N8emEpgXYQM0FjO/w2k/AU7XTxkEiBe68ZCvCxyPaAjP4wnMxEUYCu3zXIXWryx8Ez7CCXaQ43cDhwqeYsbFKVISga+rScNjCqqKK/3oae65VBR3+JivybucLvSDRk9enLqs3LQCSji0586tru2Hp+pOKl4h8TbFvu/ZkMM40YlKABc0Zae3afXusIwBDIKQ/udI3f66y3gIbkuf3lllR2UhjBy1bSR/REhC0Dosa3ykofVXWGRmWSdO/NADFXuqiXOlrLqrKKTV0Fg/LEwNMhgXJFN809S1kwyl9rIcD0sW92cSIgw64PPJ0dORIv6y8mPWcmL1+g0y4XwojqraSU79Rn8y0CtTwLzZcFskSvBn0F6aHmHKLXqg3BNwhvbCaXujBix2inOTByk6HjuCLFhr07F49rAN7tRvv+F3aFqx6JTKY/Dyu2oKPZSGUmf8sOWAp0+jUV3UW2M0yv+WHJ7ecgmkBb0Vwf1vVu/qU7UryBZzgw+KcooSKPPtm2dCrhO/xaAKbX/+imUgRNuqQl0ET/erm0PwOlOkdR2tbDMwXuktxdCTjeDe6mj218FDaJ6J7Adl2UgFIsTC4p+ZEPCp+LipMWwC2kB+podGeisoPGRKWXDb3FVS4KfxjUCGvORzs3kzqg5+ZM9FV6uK4LzsvsIfrmKk8E05D4=
    on_success: always
    on_failure: always
jobs:
  include:
    - stage: build docker images
      env:
        - TAG=$(grep "ENV VERSION" Dockerfile | awk 'NF>1{print $NF}')
        - IMGNAME=sdelrio/s3ql-gdrive
      script:
      - echo $TAG
      # x86 build
      - docker build -t $IMGNAME -f Dockerfile .
      - >
        if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
          docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
          docker tag $IMGNAME $IMGNAME:$TAG
          docker push $IMGNAME:$TAG
          docker push $IMGNAME
        fi
    - stage: test
      env:
        - TAG=$(grep "ENV VERSION" Dockerfile | awk 'NF>1{print $NF}')
        - IMGNAME=sdelrio/s3ql-gdrive
      script:
      # test x86 image
      - docker run --rm --entrypoint "/bin/ls" -ti $IMGNAME:$TAG -l /usr/local/bin
      - docker run --rm --entrypoint "/usr/local/bin/mount.s3ql" -ti $IMGNAME:$TAG --version
      - docker run --rm --entrypoint "/usr/local/bin/s3qlstat"   -ti $IMGNAME:$TAG --version
      - docker run --rm --entrypoint "/usr/local/bin/fsck.s3ql"  -ti $IMGNAME:$TAG --version
      - docker run --rm --entrypoint "/usr/local/bin/mkfs.s3ql"  -ti $IMGNAME:$TAG --version
