sudo: required
services: docker
language: generic
notifications:
  slack:
    rooms:
      secure: x1Xxi30dKk26LUWSASi5SiQvlQtTqDW5zBnZNh6lV1fSG3octj23s4FwT/pJ/j2aqNlLUq1GtXC/jssCSeCtzEovAv4XXNAqUqFP0TUfWvOWuxmUGTechxgVH66TD8oAhEuXN+LG1Vgq75uCyTkn/IBFHqOZfWXzQSpSe6XLSvYc/PF4SfVUlMV8ODFcX0ONo5kNOScpxCYCoT0DnDyw+6GreE4OAhZYhsxRwS7mCKf4c75BFHsoMKVHaxQLl1IMNXOM81X6wwH420341XAmDJ5XeUp4I+6JxNKV20OJ0WqmgWEs94XYy7koY19LRDsZAHsE9OBae+L6/4uxAIGx8pPsuBrakO8bYT0vG3JIkQZQLbYthvNTK5WFR3xjn2ARec2wLGI1icO7hY8WaPkaU7DGququOIfG3VQPKqND8WbijoEWO9eyFLvL86nqNiHlbsfdunD5qwArn1Hb+MP+a9H3veyrzyKam6S26R8SqObFD8V3Rlvie/tjQUZtIb39tsy4goMBa91vo7WLTo/pbK9GMJzSrOYjZs+TeiUWCp9VFlAUKXM3IYn+7M31NToPD9E+RFIChmQmFIOBE4xlNxow6aQxLRr0r4ET7EhFja7dwGj/zwhuqgfz1mrIKoWzsxXBmz7rTTW5mAJNpPK1QISFDXctvPry2F9Y03dXOPU=
    on_success: always
    on_failure: always
jobs:
  include:
    - stage: build docker images
      env:
        - TAG=$(grep "ENV VERSION" Dockerfile | awk 'NF>1{print $NF}')
        - IMGNAME=sdelrio/s3ql-gdrive
      script:
      - echo $TAG
      # x86 build
      - docker build -t $IMGNAME -f Dockerfile .
      - >
        if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
          docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
          docker tag $IMGNAME $IMGNAME:$TAG
          docker push $IMGNAME:$TAG
          docker push $IMGNAME
        fi
    - stage: test
      env:
        - TAG=$(grep "ENV VERSION" Dockerfile | awk 'NF>1{print $NF}')
        - IMGNAME=sdelrio/s3ql-gdrive
      script:
      # test x86 image
      - docker run --rm -ti --entrypoint sh $IMGNAME:$TAG /usr/local/bin/mount.s3ql -h

